---

- name: Check if Postgres server {{ container_command }} container already running
  shell: "{{ container_command }} ps -a -f name='qpc-db' | grep 'qpc-db'"
  become: true
  register: postgres_ps_raw
  ignore_errors: yes

- name: Remove running Postgres server {{ container_command }} container
  shell: "{{ container_command }} rm -f qpc-db"
  become: true
  ignore_errors: yes
  when:
    - postgres_ps_raw['stdout_lines'] | length > 0

- name: Start Postgres container with {{ container_command }} volume (RHEL 6, Centos 6)
  shell: "{{ container_command }} run --name qpc-db  -e POSTGRES_USER={{dbms_user}} -e POSTGRES_PASSWORD={{dbms_password}} -v /var/lib/docker/volumes/qpc-data:/var/lib/postgresql/data -d postgres:{{POSTGRES_VERSION}}"
  become: true
  when:
    - is_rhel_centos_6|bool

- name: Start Postgres container with {{ container_command }} volume (RHEL 7, Centos 7)
  shell: "{{ container_command }} run --name qpc-db  -e POSTGRES_USER={{dbms_user}} -e POSTGRES_PASSWORD={{dbms_password}} -v qpc-data:/var/lib/postgresql/data -d postgres:{{POSTGRES_VERSION}}"
  become: true
  when:
    - is_rhel_centos_7|bool

- name: Default network_pod_created to false
  set_fact:
    network_pod_created: 'false'
  when: network_pod_created is not defined

- name: Create a pod for network between the server and postgres database (RHEL 8)
  shell: "{{ container_command }} pod create --name {{ pod_name }} -p {{ server_port }}:443 -p 5432"
  become: true
  when:
    - is_rhel8|bool
    - not network_pod_created

- name: Start Postgres container with {{ container_command }} volume (RHEL 8)
  shell: "{{ container_command }} run --name qpc-db --pod {{ pod_name }} -e POSTGRES_USER={{dbms_user}} -e POSTGRES_PASSWORD={{dbms_password}} -v qpc-data:/var/lib/postgresql/data -d postgres:{{POSTGRES_VERSION}}"
  become: true
  when:
    - is_rhel8|bool

- name: Waiting for Postgres to spin up
  pause:
    seconds: 30