---

- name: Checking if server_version is defined when install_offline is true
  fail:
    msg: "server_version must be set when install_offline=true"
  when:
    - install_offline|lower == 'true'
    - server_version is not defined
