---

- name: Rename Quipucords server docker image to version specific cache name (offline install)
  command: cp -f "{{ pkg_install_dir }}{{ github_server_filename }}" "{{qpc_server_local_path}}"
  when:
    - install_offline|lower == 'true'
    - not quipucords_docker_image_present

- name: Check if local server docker image tar.gz exists
  stat:
    path: "{{qpc_server_local_path}}"
  register: find_qpc_server_local
