# Install playbook for Quipucords
---

- name: Install the Quipucords components
  hosts: localhost
  vars:
      install_server: 'true'
      install_cli: 'true'
      install_offline: 'false'
      use_supervisord: 'false'
      open_port: 'true'
      server_port: '9443'
      server_name: 'quipucords'
      container_command: 'docker'
      server_http_timeout: 120
      dbms_user: 'postgres'
      dbms_password: 'password'
      connect_job_timeout: 600
      inspect_job_timeout: 10800
      ansible_log_level: 0
  roles:
    - validate_pre_install
    - role: docker
      when: container_command|lower == 'docker'
    - role: postgres
      when: install_server|lower == 'true'
    - role: qpc_server
      when: install_server|lower == 'true'
    - role: qpc_cli
      when: install_cli|lower == 'true'
    - validate_install
