.\" Manpage for quipucords-installer
.\" Contact quipucords@redhat.com to correct errors or typos.
.TH man 8 "05 Aug 2019" "0.1.2"
.SH NAME
quipucords-installer
.SH SYNOPSIS
Installs the quipucords server and qpc cli
.SH DESCRIPTION
Installer for quipucords and qpc
.SH USAGE
quipucords-installer
.SH OPTIONS
    -h | --help   Obtain command USAGE
    -e | --extra-vars  set additional variables as key=value
.SH EXTRA VARIABLES:
    * Skip install for server:
         -e install_server=false
    * Skip install for CLI:
         -e install_cli=false
    * Perform an offline install
         -e install_offline=true
    * Quipucords server version to install (defaults to the latest release):
         -e server_version=0.0.46
    * QPC cli version to install (defaults to the latest release):
         -e cli_version=0.0.46
    * Specify if the Quipucords server port should be opened in the host firewall (defaults to true):
         -e open_port=false
    * Quipucords server port (defaults to 9443):
         -e server_port=8443
    * Postgres db user (defaults to 'postgres'):
         -e dbms_user=postgres
    * Postgres db password (defaults to 'password')
         -e dbms_password=password
.SH BUGS
No known bugs.
.SH AUTHORs
    The Quipucords tool was originally written by Chris Ham-
    bridge     <chambrid@redhat.com    (mailto:chambrid@red-
    hat.com)>,    Kevan    Holdaway     <kholdawa@redhat.com
    (mailto:kholdawa@redhat.com)>, Ashley Aiken <aaiken@red-
    hat.com (mailto:aaiken@redhat.com)>,  Cody  Myers  <cmy-
    ers@redhat.com  (mailto:cmyers@redhat.com)>, and Cecilia
    Carter    <cecarter@redhat.com     (mailto:cecarter@red-
    hat.com)>.

