#!/bin/bash
#===============================================================================
#
#          FILE:  quipucords-installer
#
#         USAGE:  ./quipucords-installer
#
#   DESCRIPTION:  Install Quipucords server and command-line components.
#
#       OPTIONS:  -h | --help   Obtain command USAGE
#                 -e | --extra-vars  set additional variables as key=value
#===============================================================================

export PATH=$PATH:$ANSIBLE_HOME/bin
#Note: The playbook path will be sed replaced in the spec file
# to match the location of where the package is being installed.
PLAYBOOKFILE="qpc_playbook.yml"
PLAYBOOKPATH=""
PLAYBOOK=$PLAYBOOKPATH$PLAYBOOKFILE

POSTGRES_VERSION='-e POSTGRES_VERSION=9.6.10'
INSTALLER_VERSION='BUILD_VERSION_PLACEHOLDER'

declare -a args
args=("$*")
args+=("$POSTGRES_VERSION")
set -- ${args[@]}

usage() {
    cat <<EOM
    Quipucords Installer
    Version: ${INSTALLER_VERSION}

    Install Quipucords server and command-line components.

    Usage:
    $(basename $0)

    Options:
    -h | --help   Obtain command USAGE
    -e | --extra-vars  set additional variables as option=value


    Extra Variables:
    * Skip install for server:
         -e install_server=false
    * Skip install for CLI:
         -e install_cli=false
    * Perform an offline install
         -e install_offline=true
    * Quipucords server version to install (defaults to the latest release):
         -e server_version=0.9.0
    * QPC cli version to install (defaults to the latest release):
         -e cli_version=0.9.0
    * Specify if the Quipucords server port should be opened in the host firewall (defaults to true):
         -e open_port=false
    * Quipucords server username (defaults to admin):
         -e server_username=cody
    * Quipucords server password (defaults to qpcpassw0rd):
         -e server_password=c0dy
    * Quipucords server user email address (defaults to admin@example.com):
         -e server_user_email=cody@hotmail.com
    * Quipucords server port (defaults to 9443):
         -e server_port=8443
    * Postgres db user (defaults to 'postgres'):
         -e dbms_user=postgres
    * Postgres db password (defaults to 'password')
         -e dbms_password=password
EOM
    exit 0
}

if [[ ($1 == "--help") ||  ($1 == "-h") ]]
then
  usage;
fi

for arg in $args; do
  if [[ $arg != "-e" ]]; then
    IFS='=' read -r -a temp_arr <<< "$arg"
    key=${temp_arr[0]}
    value=${temp_arr[1]}
    printf -v $key "$value"
  fi
done

if [[ $EUID -ne 0 ]]
then
  echo ansible-playbook $PLAYBOOK -v -K $*
  ansible-playbook $PLAYBOOK -v -K $*
else
  echo ansible-playbook $PLAYBOOK -v $*
  ansible-playbook $PLAYBOOK -v $*
fi

if [ $? -eq 0 ]
then
  unset args
  echo "Installation complete."
else
  unset args
  echo "Installation failed. Review the install logs."
  exit 1
fi