---

- name: Testing yum module difference
  hosts: localhost
  tasks:
    - name: Test if yum list can tell if a package is installed (ansible)
      yum:
        list: ansible
      register: have_ansible_raw
      become: true
      ignore_errors: yes

    - name: Set boolean for if yumstate of ansible is installed
      set_fact:
        have_ansible: "{{ have_ansible_raw.results[0].yumstate == 'installed' }}"
      when:
        - have_ansible_raw["results"] is defined
        - have_ansible_raw["results"]|length > 0

    - name: Ensure that the have_ansible is true & test have_ansible works as a boolean in the when condition
      debug:
        var: have_ansible
      when:
        - have_ansible

    - name: Test if yum list can tell if a package is not installed (fabtests)
      yum:
        list: fabtests
      register: have_fabtests_raw
      become: true
      ignore_errors: yes

    - name: Set boolean for if yumstate of fabtests is installed
      set_fact:
        have_fabtests: "{{ have_fabtests_raw.results[0].yumstate == 'installed' }}"
      when:
        - have_fabtests_raw["results"] is defined
        - have_fabtests_raw["results"]|length > 0

    - name: Ensure that the have_fabtests is false
      debug:
        var: have_fabtests
      when:
        - have_fabtests is defined
        - not have_fabtests

    - name: Prove that our previous method performed an install
      yum:
        name: fabtests
        state: installed
      register: old_method_raw
      become: true
      ignore_errors: yes

    - name: Prove that the old method shows packages as being installed
      debug:
        var: old_method_raw

    - name: Check if fabtests is now installed
      yum:
        list: fabtests
      register: fabtests_raw
      become: true
      ignore_errors: yes

    - name: Set have_fabtest
      set_fact:
        have_fabtests: "{{ fabtests_raw.results[0].yumstate == 'installed' }}"
      when:
        - fabtests_raw["results"] is defined
        - fabtests_raw["results"]|length > 0

    - name: Prove that fabtests is now installed
      debug:
        var: have_fabtests

    - name: Check if EPEL is installed with yum
      yum:
        list: epel-release
      register: have_epel_raw
      become: true
      ignore_errors: yes

    - name: Set have_epel
      set_fact:
        have_epel: "{{ have_epel_raw.results[0].yumstate == 'installed' }}"
      when:
        - have_epel_raw["results"] is defined
        - have_epel_raw["results"]|length > 0
